site_name: TL Game Development
theme:
  name: material
  palette:
    - scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  generator: false
copyright: Copyright &copy; 2021 Owen Bartolf
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - footnotes
  - attr_list